### ISSUE TITLE
Smart gas detector support?

### ISSUE THREAD

**Issue by KnNLmS** [YinHangCode/homebridge-mi-aqara#1]
Hi,

Do you plan to add smart gas detector support?

And is it possible to integrate yeelight platform too?

Thanks.

**Comment by YinHangCode** [comment]
Hi, KnNLmS:
smart gas detector currently belongs to the crowd funding stage, when XiaoMi release official version, I will consider adding.

**Comment by KnNLmS** [comment]
Actually i have one and using with Mi home application. I believe you're
waiting for documentation about it. I hope it would be released soon.
Thanks.

**Comment by YinHangCode** [comment]
gas sensor has already added at version 0.3.0, but I don't have that device. you can test it. if it have bugs, contact me.

**Comment by KnNLmS** [comment]
Gas sensor shown in Home kit but gas alarm can't be detected by homekit. Mi
home working well.

I tested button again and it is sure no response(no indication about press)
on homekit. If you want i can make a video for you.

**Comment by YinHangCode** [comment]
Well, my email is 141564@qq.com. Please send video to me, Thank you.
Gas sensor I try fix it.
