### ISSUE TITLE
Other plugins based on local network package

### ISSUE THREAD

**Issue by acc-ua** [YinHangCode/homebridge-mi-aqara#108]
I am working on a plugin that sends direct commands to gateway to play internal tones. 
Its mostly based on your plugins, and uses {"cmd":"write"....} command with dynamic gateway token that is listening with broadcast messages.

Looks like homebridge-mi-aqara and my plugin CAN'T work at the same time.
Is it possible to have several plugins based on _local network package_?  Is there any workaround?

Thanks in advance.

**Comment by acc-ua** [comment]
actually, after turning my plugin off it looks like I still don't receive any updates from sensors... so, maybe the problem is not in plugins conflict.  But, please let me know if there can be any problems with several plugins working on local network package protocol.

**Comment by acc-ua** [comment]
Not sure what going wrong with several plugins that uses datagram sockets on the same machine, but I could not make them working normally with write requests both.
So, I just forked you plugin and added my buttons to play gateway's melodies into the plugin. now it works :)

So, issue can be closed;

**Comment by YinHangCode** [comment]
About the conflict, I personally suggest that each homebridge plug uses a separate homebridge, the reason is as follows:
1.faster response.
2.plugs do not affect each other.
3.the entire homebridge will not crash because one of the plugins crashed.
4.homebridge is bridge, it's not platform.

**Comment by acc-ua** [comment]
Probably, you are right, this way should be the best to eliminate any kind of interferences.
By the way, in my fork (https://github.com/acc-ua/homebridge-mi-aqara) I've added functionality for Gateway so there can be setup virtual buttons that play some tone/melody from gateway (built-in /user-defined).

If you think its useful, you can add that functionality to you plugin or I can make a pull request.

**Comment by YinHangCode** [comment]
I have not added this feature because of I feel less people use it.
Now, since some people need it, then the next version will be added.

**Comment by acc-ua** [comment]
Ok, great
