### ISSUE TITLE
help me configure

### ISSUE THREAD

**Issue by ZoltXs** [YinHangCode/homebridge-mi-aqara#109]
hello, could you tell me how to see mac address and password of the Gateway, sensor ... of xiaomi, with iphone or macbook, to be able to configure it.
Thank you.

**Comment by a900927** [comment]
Configuration

Open Aqara gateway's settings, enable local network protocol.
Please follow the steps in this thread: http://bbs.xiaomi.cn/t-13198850. It's in Chinese so you might need a translator to read it.
To control the devices, put gateway's MAC address (lower case without colon) and password (keep original and case sensitive) to ~/.homebridge/config.json.

**Comment by ZoltXs** [comment]
it would take an Android phone, there is no other way

**Comment by ZoltXs** [comment]
I do not have android

**Comment by linxingyulxy** [comment]
you need to download “米家” app in APP Store.  it can use in iphone.

**Comment by a900927** [comment]
@ZoltXs you can install BlueStacks or others android emulator for pc or mac.
and you can download mijia in App store,in the about page ,click the blank area(many times)

**Comment by iCarl** [comment]
There is absolutely no need to use a anddroid phone or an emulator to do this.
Just use the Mi Home app on the iPhone.

First, you tap the upper right corner
![img_0037](https://user-images.githubusercontent.com/4193514/33216072-9a52e8ce-d132-11e7-8249-fafadd7240d9.jpg)

Then select "About":
![img_0040](https://user-images.githubusercontent.com/4193514/33216085-aeeb8124-d132-11e7-8d53-a78d2ce4c7c1.jpg)


Then you tap the empty field in the bottom five times
![img_0041](https://user-images.githubusercontent.com/4193514/33216091-bde23772-d132-11e7-8672-97b902baeb88.jpg)

**Comment by ZoltXs** [comment]
Many thanks to all for the help, especially to iCarl, also works on iphone, by clicking on the center below.
Thank you.

**Comment by ZoltXs** [comment]
I have managed to configure config.json file correctly, I run homebridge and everything is correct but I can not see xiaomi accessories at home iphone app.
Someone can help me what I'm doing wrong or what I have to do. I currently have thermostat and bosch and if I see but xiaomi accessories do not.
Thank you.
![captura de pantalla 2017-11-25 a las 19 47 50](https://user-images.githubusercontent.com/3195969/33233690-698f8218-d21a-11e7-968d-74925d34c269.png)
![captura de pantalla 2017-11-25 a las 19 48 44](https://user-images.githubusercontent.com/3195969/33233692-6c2c85b6-d21a-11e7-804e-4ee101679422.png)
![captura de pantalla 2017-11-25 a las 19 49 17](https://user-images.githubusercontent.com/3195969/33233693-6f277294-d21a-11e7-91bf-31bae1e33b1b.png)

**Comment by ZoltXs** [comment]
Solved, the problem was in the password of the gateway, change of capitals by lowercase and everything correct.
Thank you.

**Comment by quiquepr** [comment]
I have configured the MiAqara plug in but cannot get my cube accessory to load.  I am using the G2H Camera, hub and have no other Aqare deveceis, trying to get Cube to work with homekit scenes/automations. Platform seems to load fine, but no accessories are loaded or show up in homebridge. See Json and logs below. 


Json
{
            "platform": "MiAqaraPlatform",
            "name": "MiAqaraPlatform",
            "gateways": {
                "554ef44xxxxxx": "",
                "ip": "192.168.1.7"
            },
            "defaultValue": {
                "158D00051Exxxx": {
                    "MagicSquare_StatelessProgrammableSwitch_Flip90": {
                        "name": "Media room magic square flip90"
                    },
                    "MagicSquare_StatelessProgrammableSwitch_Flip180": {
                        "name": "Media room magic square flip180"
                    },
                    "MagicSquare_StatelessProgrammableSwitch_Move": {
                        "name": "media room magic square Move"
                    },
                    "MagicSquare_StatelessProgrammableSwitch_TapTwice": {
                        "name": "media room magic square TapTwice"
                    },
                    "MagicSquare_StatelessProgrammableSwitch_ShakeAir": {
                        "name": "media room magic square ShakeAir"
                    },
                    "MagicSquare_StatelessProgrammableSwitch_Rotate": {
                        "name": "media room magic square Rotate"
                    },
                    "MagicSquare_Switch_VirtualFlip90": {
                        "name": "media room Cube VFlip90"
                    },
                    "MagicSquare_Switch_VirtualFlip180": {
                        "name": "media room Cube VFlip180"
                    },
                    "MagicSquare_Switch_VirtualMove": {
                        "name": "media room Cube Vmove"
                    },
                    "MagicSquare_Switch_VirtualTapTwice": {
                        "name": "media room Cube V2Tap"
                    },
                    "MagicSquare_Switch_VirtualShakeAir": {
                        "name": "media room Cube vShake"
                    }
                }
            }
        },

Logs
11:11:28 PM] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[2/15/2021, 11:11:28 PM] ---
[2/15/2021, 11:11:28 PM] Loaded plugin: homebridge-platform-lightify@0.3.7
[2/15/2021, 11:11:28 PM] Registering platform 'homebridge-platform-lightify.Lightify'
[2/15/2021, 11:11:28 PM] ---
[2/15/2021, 11:11:29 PM] Loaded plugin: homebridge-sensibo-ac@2.0.23
[2/15/2021, 11:11:29 PM] Registering platform 'homebridge-sensibo-ac.SensiboAC'
[2/15/2021, 11:11:29 PM] ---
[2/15/2021, 11:11:29 PM] Loaded plugin: @milo526/homebridge-tuya-web@1.0.0
[2/15/2021, 11:11:29 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[2/15/2021, 11:11:29 PM] ---
[2/15/2021, 11:11:29 PM] Loading 6 platforms...
[2/15/2021, 11:11:29 PM] [Config] Initializing config platform...
[2/15/2021, 11:11:29 PM] [Config] Running in Service Mode
[2/15/2021, 11:11:29 PM] [Hue B1] Initializing Hue platform...
[2/15/2021, 11:11:30 PM] [Hue B1] homebridge-hue v0.12.22, node v14.15.5, homebridge v1.1.7
[2/15/2021, 11:11:30 PM] [Hue B1] searching bridges and gateways
[2/15/2021, 11:11:30 PM] [MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]**************************************************************
[2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]           MiAqaraPlatform v0.8.0 By YinHang
[2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-aqara  
[2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]                                         QQ Group: 107927710  
[2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]**************************************************************
[2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]start success...
[2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]config gateways: 554ef44ccb413, ip
[2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]binding to the default interface
[2/15/2021, 11:11:30 PM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[MiAqaraPlatform] [INFO]Aqara LAN protocol server is listening on port: 9898

**Comment by ctsitselis** [comment]
> I have configured the MiAqara plug in but cannot get my cube accessory to load. I am using the G2H Camera, hub and have no other Aqare deveceis, trying to get Cube to work with homekit scenes/automations. Platform seems to load fine, but no accessories are loaded or show up in homebridge. See Json and logs below.
> 
> Json { "platform": "MiAqaraPlatform", "name": "MiAqaraPlatform", "gateways": { "554ef44xxxxxx": "", "ip": "192.168.1.7" }, "defaultValue": { "158D00051Exxxx": { "MagicSquare_StatelessProgrammableSwitch_Flip90": { "name": "Media room magic square flip90" }, "MagicSquare_StatelessProgrammableSwitch_Flip180": { "name": "Media room magic square flip180" }, "MagicSquare_StatelessProgrammableSwitch_Move": { "name": "media room magic square Move" }, "MagicSquare_StatelessProgrammableSwitch_TapTwice": { "name": "media room magic square TapTwice" }, "MagicSquare_StatelessProgrammableSwitch_ShakeAir": { "name": "media room magic square ShakeAir" }, "MagicSquare_StatelessProgrammableSwitch_Rotate": { "name": "media room magic square Rotate" }, "MagicSquare_Switch_VirtualFlip90": { "name": "media room Cube VFlip90" }, "MagicSquare_Switch_VirtualFlip180": { "name": "media room Cube VFlip180" }, "MagicSquare_Switch_VirtualMove": { "name": "media room Cube Vmove" }, "MagicSquare_Switch_VirtualTapTwice": { "name": "media room Cube V2Tap" }, "MagicSquare_Switch_VirtualShakeAir": { "name": "media room Cube vShake" } } } },
> 
> Logs 11:11:28 PM] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform' [2/15/2021, 11:11:28 PM] --- [2/15/2021, 11:11:28 PM] Loaded plugin: homebridge-platform-lightify@0.3.7 [2/15/2021, 11:11:28 PM] Registering platform 'homebridge-platform-lightify.Lightify' [2/15/2021, 11:11:28 PM] --- [2/15/2021, 11:11:29 PM] Loaded plugin: homebridge-sensibo-ac@2.0.23 [2/15/2021, 11:11:29 PM] Registering platform 'homebridge-sensibo-ac.SensiboAC' [2/15/2021, 11:11:29 PM] --- [2/15/2021, 11:11:29 PM] Loaded plugin: @milo526/homebridge-tuya-web@1.0.0 [2/15/2021, 11:11:29 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform' [2/15/2021, 11:11:29 PM] --- [2/15/2021, 11:11:29 PM] Loading 6 platforms... [2/15/2021, 11:11:29 PM] [Config] Initializing config platform... [2/15/2021, 11:11:29 PM] [Config] Running in Service Mode [2/15/2021, 11:11:29 PM] [Hue B1] Initializing Hue platform... [2/15/2021, 11:11:30 PM] [Hue B1] homebridge-hue v0.12.22, node v14.15.5, homebridge v1.1.7 [2/15/2021, 11:11:30 PM] [Hue B1] searching bridges and gateways [2/15/2021, 11:11:30 PM] [MiAqaraPlatform] Initializing MiAqaraPlatform platform... [2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]************************************************************** [2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO] MiAqaraPlatform v0.8.0 By YinHang [2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO] GitHub: https://github.com/YinHangCode/homebridge-mi-aqara [2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO] QQ Group: 107927710 [2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]************************************************************** [2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]start success... [2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]config gateways: 554ef44ccb413, ip [2/15/2021, 11:11:30 PM] [MiAqaraPlatform] [INFO]binding to the default interface [2/15/2021, 11:11:30 PM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform... [MiAqaraPlatform] [INFO]Aqara LAN protocol server is listening on port: 9898

Hello. i am trying to do the same using the same setup. cobe + G2H Camera.

Did you ever fix this? can you help me out please?
thanks in advance,
christos
