### ISSUE TITLE
gateway join permission (question)

### ISSUE THREAD

**Issue by astrojetson8** [YinHangCode/homebridge-mi-aqara#110]
what does gateway join permission toggle button do?

**Comment by ZoltXs** [comment]
No hace nada, simplemente es una prueba, pero hay otro boton del gateway que controla la luz de gateway.

**Comment by YinHangCode** [comment]
this button allows you to add new devices directly in homekit instead of opening the MiJia(MiHome) app.

**Comment by astrojetson8** [comment]
@YinHangCode  nice work!!!

**Comment by ZoltXs** [comment]
Some way to set a switch to activate or deactivate the alarm.

**Comment by phenomeus** [comment]
@YinHangCode and how can I do this? can you give a little tutorial how to use "join permission switch"?
