### ISSUE TITLE
zigbee插座开关经常出错

### ISSUE THREAD

**Issue by saury** [YinHangCode/homebridge-mi-aqara#113]
插座经常无响应抽风， error详情见图，home.app中显示无响应，米家.app中显示离线。此时貌似必须手动去按一下插座的实体开关才能恢复正常，套装中别的都没这种问题，求解。。。
<img width="568" alt="2017-11-29 2 59 02" src="https://user-images.githubusercontent.com/3221192/33362134-e83f8baa-d515-11e7-96d7-00bff158b5b0.png">

**Comment by YinHangCode** [comment]
从你发的日志上看 网关给的信息中的当前插座状态值是unknown 所以无法知道当前开关的状态是开的还是关的 所以就显示未响应状态了

**Comment by saury** [comment]
谷歌了下，应该是插座硬件本身或距离网关太远导致的无响应。
