### ISSUE TITLE
Motion Sensor Add Timer?

### ISSUE THREAD

**Issue by SeydX** [YinHangCode/homebridge-mi-aqara#124]
Hello,

i have several xiaomi motion sensors and i am using it with this plugin.

I am not able to set a timer to go off for the motions sensor. Before my gateway arrived, i have used it with „Raspbee“ (its a zigbee discovery gateway like hue) and with Raspbee it was possible to set timer...

Is it hard to make this possible for the motion sensors? It would be very nice!

Thanks so much for the great plugin

Hope anyone has a solution for my problem

Thanks all

**Comment by WEZANGO** [comment]
Agree, that would be very useful
