### ISSUE TITLE
请问空调伴侣可以替代网关吗？

### ISSUE THREAD

**Issue by Raccooon** [YinHangCode/homebridge-mi-aqara#136]
一直不成功，读不出配件
转而怀疑是否不支持空调伴侣？
我的这套系统中，没有网关，只有空调伴侣（自带网关）

**Comment by YinHangCode** [comment]
空调伴侣目前是米家app里开放了局域网通信协议的入口，但是设备的固件还不支持这个功能。
之前问过绿米，说之后会开放，所以。。。等绿米更新固件吧。。。。
