### ISSUE TITLE
lux sensor value

### ISSUE THREAD

**Issue by astrojetson8** [YinHangCode/homebridge-mi-aqara#14]
fyi: looks like the default value for lux from gateway is around 360lux even when it's pitch dark. 
https://msdn.microsoft.com/en-us/library/windows/desktop/dd319008(v=vs.85).aspx

**Comment by sendorm** [comment]
Someone has pointed out the fact from a xiaomi document that the lux sensor gives values between 300-1300. I went ahead and subtracted 300 from the reported value. Now it shows between 0-1000. Which for me is a better representation.

**Comment by sendorm** [comment]
Here is the link

https://github.com/lazcad/homeassistant/pull/46

**Comment by astrojetson8** [comment]
@sendorm  oh cool, thanks, and it make sense. are you manually subtracting 300 ?
@YinHangCode  
option 1. update this in code?
option 2.  add default start lux value via config 
option 3. i don't know

**Comment by sendorm** [comment]
Yeah, I am directly subtracting 300 in the code. So the reported value is between 0-1000. But still they are not good values. I tried to find a multiplier using the mi flora sensor (which seems to have a much better represantation). The relation might even be quadratic, I might check into that.

But in the end it is not necessary, just get the values for your normal usage and create automations accordingly.

**Comment by astrojetson8** [comment]
@YinHangCode thanks for adding this to your latest release.

**Comment by YinHangCode** [comment]
![1](https://user-images.githubusercontent.com/15974677/28635161-366cc944-726c-11e7-9db9-728f14c98b30.PNG)
![123](https://user-images.githubusercontent.com/15974677/28635162-36a11046-726c-11e7-865d-f3a45a87d64b.png)

@astrojetson8 @sendorm It looks like -300 is not a good value.

**Comment by sendorm** [comment]
yeah some users on the home assistant site also reported that 300 offset is not working for them too. 279 was the least reported as I recall.

**Comment by YinHangCode** [comment]
@sendorm maybe -279 is the most suitable value.

**Comment by sendorm** [comment]
Maybe but the document here states that the values are between 300-1300.
https://github.com/louisZL/lumi-gateway-local-api/blob/master/网关.md

Some one else can say that his values goes down to 275 for instance, so a zero check is a must. 
But of course it is your decision. You can make it 279 and put a negative check. That way no one will get an erroneous negative lux value.

**Comment by YinHangCode** [comment]
@sendorm yes, the document description is between 300-1300, but In fact, this is not the case.
following code should be better:
`var illumination = data['illumination'] illumination / 1.0 - 279;`
and
`illCharacteristic.updateValue(illumination > 0 ? illumination : 0);`

**Comment by sendorm** [comment]
Yes, good solution. Thank you.

**Comment by astrojetson8** [comment]
@YinHangCode sounds good.
