### ISSUE TITLE
Aqara Gateway Camera

### ISSUE THREAD

**Issue by Wang249** [YinHangCode/homebridge-mi-aqara#146]
Can the Aquara Gateway Camera be used as the gateway for this? How do I set it up? I'm having trouble finding the mac address and password.

Thanks!

https://xiaomi-mi.com/ip-cameras/xiaomi-aqara-smart-camera-gateway-edition-white/

**Comment by tickerey** [comment]
Same here

**Comment by soomrox** [comment]
I have got this camera now. I can get to the IP address and the GW mac address but cannot find the password. Would love to be be added in your supported devices. Thanks

**Comment by petemagnusson** [comment]
It looks like the developer mode istn fully avalible yet, on Android pressing the SW version will bring up the same menu as on the Server, and you can enable LAN access but it will just timeout when you select save.

**Comment by ileler** [comment]
@all This device does not currently support LAN protocols
