### ISSUE TITLE
Xiaomi QBKG03LM Aqara Wall Switch doesn't work

### ISSUE THREAD

**Issue by kdamsk** [YinHangCode/homebridge-mi-aqara#15]
Hi,
Xiaomi QBKG03LM Aqara Wall Switch doesn't work.
I see it in Homekit, it shows status of all 2 switches, but when i'm trying to switch it - nothing happens.
From MiHome app it works fine.

**Comment by sendorm** [comment]
Have you tried with sid-> all small letters and password-> all capital letters?

**Comment by kdamsk** [comment]
After changing password to capital letters - it's working. Thank you.
