### ISSUE TITLE
Battery Level at 51% all time?

### ISSUE THREAD

**Issue by malmentm** [YinHangCode/homebridge-mi-aqara#164]
Every device shows battery level of 51% ?

**Comment by malmentm** [comment]
Ignore this.

**Comment by theo-69** [comment]
then close it and or remove it :-(

**Comment by YinHangCode** [comment]
This value is based on the voltage. It may not be very accurate.
Of course, he wasn't always 51%.
![img_3551](https://user-images.githubusercontent.com/15974677/41885781-fa6085d6-792b-11e8-91af-82318a38ef96.PNG)
