### ISSUE TITLE
Activate alarm in Homekit

### ISSUE THREAD

**Issue by Knol010** [YinHangCode/homebridge-mi-aqara#185]
Is there a way to get a virtual switch to trigger/untrigger the alarm function from the gateway with Homekit?
I only use Homekit and i prefer to have the ability to set the alarm with Homekit with a scene like "Going to sleep"

Thanks for the help!

**Comment by tomsteenbakkers** [comment]
Try this plugin. This enables you to switch the security on the gateway on (armed) and off (disarmed)

https://github.com/YinHangCode/homebridge-mi-gateway-security

**Comment by Knol010** [comment]
Thanks Tom its working!
