### ISSUE TITLE
Moving accessories to Europe servers

### ISSUE THREAD

**Issue by tomsteenbakkers** [YinHangCode/homebridge-mi-aqara#187]
I have set the Mi Home app to China mainland and everything is working. Since 2 weeks I now can select European servers. But when switching I need to register all accessories with the gateway. 

If I do this, will this effect the plugin?

**Comment by theo-69** [comment]
just try it out.

**Comment by tomsteenbakkers** [comment]
Try it and it’s not working. After setting the Mi app to Europe region. You lose all the accessories. If you want to add them there are no accessories listed only the Bluetooth items. You can’t even add the gateway. So we are stuck with mainland China

**Comment by theo-69** [comment]
OK good to know. Thanks!
