### ISSUE TITLE
门窗传感器状态经常出错，请Mr.Yin考虑改进

### ISSUE THREAD

**Issue by xcray** [YinHangCode/homebridge-mi-aqara#193]
就是开门再关门之后，米家app里的状态是正确的（日志里有时间在一分钟之内的开和关两条记录）、但homebridge却说门一直开着。
这种情况约每天都会出现一两次，虽然大多数时候都没问题，但这个概率还是有些高。门窗传感器的重要性不言而喻，所以希望作者能抽空考虑一下这个问题。
对node很不熟悉，代码看不懂。如果不是bug的话，能否在检测到门窗开启后定时刷新状态？这样即使由于漏掉了关门的消息也可以在短时间内自己纠正过来。

再次感谢作者这么好的插件！

**Comment by xcray** [comment]
问题弄清楚了，根本原因是网卡层面的丢包，不过如果程序在检测到门被打开之后，每隔几秒检查一下最新状态直至关闭，对网络环境不太好的使用者来说应该是一个不错的特性。

**Comment by YinHangCode** [comment]
可以把SyncValue打开，这样每次打开homekit的时候 会去主动同步最新的值。

**Comment by xcray** [comment]
@YinHangCode 感谢回复！其实网络环境还可以，5G的wifi，只是当时跑hb的那台电脑网卡有问题。
