### ISSUE TITLE
Update to 0.6.9 ? How? Does not seem to be avaible?

### ISSUE THREAD

**Issue by malmentm** [YinHangCode/homebridge-mi-aqara#199]
How do i update to 0.6.9? Can only find 0.6.8

**Comment by YinHangCode** [comment]
please wait, 0.6.9 is currently in the dev state. I and my friends in the QQ group are testing his stability.

**Comment by malmentm** [comment]
@YinHangCode Great! Keep up the good work!

**Comment by 350d** [comment]
@YinHangCode can you please fix virtual switch functionality in this update? #142
