### ISSUE TITLE
Aqara Vibration Sensor

### ISSUE THREAD

**Issue by Kohle81** [YinHangCode/homebridge-mi-aqara#220]
Hello,
is it possible to include this new Sensor with this plugin?

https://m.aliexpress.com/item/32890037513.html?pid=808_0000_0101&spm=a2g0n.search-amp.list.32890037513&

**Comment by DJay-X** [comment]
@YinHangCode Support for the Vibration Sensor would be awesome. Thanks for your great work, ongoing development and sharing with us. You have a thankful community. 🙏🏼
![75582c92-3bef-47b7-a44d-c32751f56ba6](https://user-images.githubusercontent.com/3874239/44539639-fd872380-a704-11e8-9de4-030d4da1f319.jpeg)

**Comment by paolotremadio** [comment]
Any help would be more than welcome. I'm trying to help the deCONZ team to figure out what the sensor values are.

See: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/748

**Comment by DJay-X** [comment]
@YinHangCode Thanks for Version 0.7.3 and support for Vibration Sensor 💕👍🏻
