### ISSUE TITLE
Do not remove devices

### ISSUE THREAD

**Issue by permadm** [YinHangCode/homebridge-mi-aqara#221]
Devices removed from mihub are not removed from the homekit. The instruction in config.json does not help for all devices. If several devices appear in the homekit under one serial number, they can not be removed via config.json.

This device has been removed from mihub. How do I remove it from homekit?

![scr 2018-08-19 13 42 09](https://user-images.githubusercontent.com/23650010/44307106-f931d200-a3b5-11e8-8a3a-339d5ca7f598.jpg)

e47b is one device. How can I remove it?
The following configuration does not work.
![image](https://user-images.githubusercontent.com/23650010/44307153-ac9ac680-a3b6-11e8-8743-e8509f92882b.jpeg)

**Comment by lboue** [comment]
+1 👍

**Comment by YinHangCode** [comment]
···
"defaultValue": {
	"158d0001000012": {
		"DuplexButton86_StatelessProgrammableSwitch_Left": {
			"name": "dining room 86 button left"
		},
		"DuplexButton86_Switch_VirtualSinglePress_Left": {
			"name": "dining room 86 button left virtual single press",
			"disable": true
		},
		"DuplexButton86_StatelessProgrammableSwitch_Right": {
			"name": "dining room 86 button right"
		},
		"DuplexButton86_Switch_VirtualSinglePress_Right": {
			"name": "dining room 86 button right virtual single press",
			"disable": true
		},
		"DuplexButton86_StatelessProgrammableSwitch_Both": {
			"name": "dining room 86 button both"
		},
		"DuplexButton86_Switch_VirtualSinglePress_Both": {
			"name": "dining room 86 button both virtual single press",
			"disable": true
		}
	}
}
···
For more information about config, Please refer to file `sampleConfig.json`.

**Comment by permadm** [comment]
Thanks! Its work!
![image](https://user-images.githubusercontent.com/23650010/44477747-f56fab00-a654-11e8-9a68-5796313bd25f.png)

**Comment by orevron** [comment]
Hi I'm having the same issue trying to remove button, temperature sensor and contact sensor with no success can you please assist?

this is my configuration:
```json
{
            "platform": "MiAqaraPlatform",
            "autoRemoveAccessoryInterval": 100,
            "gateways": {
                "f0b429cc8504": {
                    "password": "**********",
                    "ip": "x.x.x.x"
                },
                "defaultValue": {
                    "Global": {
                        "ignoreWriteResult": false,
                        "syncValue": true
                    },
                    "158d000588ad0d": {
                        "ContactSensor_ContactSensor": { "disable": true }
                    },
                    "158d00042d5543": {
                        "TemperatureAndHumiditySensor_TemperatureSensor": { "disable": true},
                        "TemperatureAndHumiditySensor_HumiditySensor": { "disable": true }
                    },
                    "158d0002c48270": {
                        "Button_Switch_VirtualDoublePress": { "disable": true },
                        "Button_Switch_VirtualSinglePress": { "disable": true },
                        "Button_StatelessProgrammableSwitch": { "disable": true }
                    }
                }
            }
        },
```
