### ISSUE TITLE
New devices support

### ISSUE THREAD

**Issue by Dengor1984** [YinHangCode/homebridge-mi-aqara#23]
Hello!
Thank you for a super plugin!
Can you, please, add to supported devices NEW square sensors (temperature and door/window open) and Curtain Controller!!!

**Comment by kdamsk** [comment]
Also please add new square button and new human body/movement detection sensor
Many thanks!

**Comment by Dengor1984** [comment]
Square sensors works fine in homekit, thank you for a good job!

**Comment by YinHangCode** [comment]
@Dengor1984 It is a pity that there is no pressure sensors accessory in currently homekit accessory. so square sensors only supported temperature and humidity in homekit now. I hope apple add pressure sensors accessory in ios11 homekit.

**Comment by kdamsk** [comment]
Thanks!
Does lux(light measure) sensor supporting in new motion sensor?

**Comment by YinHangCode** [comment]
@kdamsk yeah
