### ISSUE TITLE
一个反馈

### ISSUE THREAD

**Issue by LASER-Yi** [YinHangCode/homebridge-mi-aqara#24]
对于原先版本的homebridge-aqara中，有一个这样的功能：

> If you like to use Light Bulb type for Light Switch to make grandma Siri happy, like me, you can set the following in the config.

        {
            "platforms": [
            {
                "platform": "AqaraPlatform",
                ...
                "fakeLightBulbForLightSwitch": true,
                ...
            }]
        }
        
如果能在之后的版本加入就更好了。

当然也十分感谢开发者所做的工作，能在Homekit下更好管理米家设备（鞠躬

**Comment by YinHangCode** [comment]
在家庭app里可以直接设置插座的类型为灯啊。

**Comment by LASER-Yi** [comment]
是的，但是相应的Home App就不能使用一些操作，比如在日落后检测到人自动开灯。如果作者方便的话可以用网关自带的灯和开关控制的灯比较一下，他们的差别还是蛮大的:D

**Comment by YinHangCode** [comment]
知道了，下一个版本考虑修改一下。

**Comment by LASER-Yi** [comment]
十分感激ʕ •ᴥ•ʔ
