### ISSUE TITLE
the button is not support in iOS 11 PB2

### ISSUE THREAD

**Issue by Fetiz** [YinHangCode/homebridge-mi-aqara#29]
Try to enable the button of my xiaomi kits. but the homebridge always display an unsupport devices.

**Comment by astrojetson8** [comment]
@Fetiz it works for me. also, please see my earlier feedback: https://github.com/YinHangCode/homebridge-mi-aqara/issues/2#issuecomment-309394998

**Comment by Fetiz** [comment]
@astrojetson8 3 hours after added the button on iPhone, I checked my iPad home app, the button is still not support.
