### ISSUE TITLE
How to get temperature and humidity data from MQTT?

### ISSUE THREAD

**Issue by shane-zhang** [YinHangCode/homebridge-mi-aqara#293]
Is there any way to extract the temperature or humidity from the child device periodically?
In the other project like "Homebridge Mi Hygrothermograph", it will publish this information to the MQTT based on the Bluetooth signal interval.
So is that possible for the ZigBee version sensor?

**Comment by shane-zhang** [comment]
I found it in the sensor_ht topic. No further problems.

**Comment by shane-zhang** [comment]
`
/homebridge-mi-aqara {"cmd":"report","model":"sensor_ht","sid":"158d0003163075","short_id":5822,"data":"{\"temperature\":\"2599\"}"}
/homebridge-mi-aqara/report {"cmd":"report","model":"sensor_ht","sid":"158d0003163075","short_id":5822,"data":"{\"temperature\":\"2599\"}"}
/homebridge-mi-aqara/158d0003163075 {"cmd":"report","model":"sensor_ht","sid":"158d0003163075","short_id":5822,"data":"{\"temperature\":\"2599\"}"}
/homebridge-mi-aqara/158d0003163075/report {"cmd":"report","model":"sensor_ht","sid":"158d0003163075","short_id":5822,"data":"{\"temperature\":\"2599\"}"}
/homebridge-mi-aqara {"cmd":"report","model":"sensor_ht","sid":"158d0003163075","short_id":5822,"data":"{\"humidity\":\"3489\"}"}
/homebridge-mi-aqara/report {"cmd":"report","model":"sensor_ht","sid":"158d0003163075","short_id":5822,"data":"{\"humidity\":\"3489\"}"}
/homebridge-mi-aqara/158d0003163075 {"cmd":"report","model":"sensor_ht","sid":"158d0003163075","short_id":5822,"data":"{\"humidity\":\"3489\"}"}
/homebridge-mi-aqara/158d0003163075/report {"cmd":"report","model":"sensor_ht","sid":"158d0003163075","short_id":5822,"data":"{\"humidity\":\"3489\"}"}
`

**Comment by MustardMaster** [comment]
Apologies. Rookie here digging up an old post. 
Any chance you post an example/config of how you got this to work. Have my Aqara Hub in Homekit mode and connected up fine. But trying to use this plugin to capture Temp Data to send via MQTT to other devices. 

Gate way is connected, Sensor seems to be connected, MQTT is setup and I get a "virtual_iam" messsage on start up, but no sensor data. Evidently i'm missing something.
