### ISSUE TITLE
可不可以在首页把支持的设备缩写列一下

### ISSUE THREAD

**Issue by biogerm** [YinHangCode/homebridge-mi-aqara#31]
在首页里面写，如果想预设设备的名称，需要填写如下

"defaultValue": {
            "158d0001000001": {
                "Mag": {
                    "name": "entrance door"
                }
            },

的内容，其中 "Mag"，如果我没理解错代码，应该是保留字段，能不能在文档的相同位置把所有保留字段都列出来？这样方便大家在写配置的时候填写正确的缩写。

**Comment by biogerm** [comment]
还有就是 那些列出来的 version 2，好像并不是 version 2，而是 Aqara 自己的版本。。。写成 v2 有点 confusing...

**Comment by YinHangCode** [comment]
在sampleConfig.json里有全部的、顺序和readme.md里一样。

**Comment by YinHangCode** [comment]
这次新出的插件，有些确实是功能增强了，所以定为v2版吧。

**Comment by biogerm** [comment]
原来在 sample 里面，我觉得可以在 readme 里面 refer 一下，这样下次大家看到了就知道去哪里找了。至于 Aqara 的智能设备，我感觉是子公司单独出的吧，如果是二代的话一代应该会下架，如果现在就叫 v2那以后米家的二代出了就不好办了。是不是叫 Aqara 版比较好一点？比如 MagAqara 之类。

**Comment by biogerm** [comment]
ps 魔方的方应该是 cube 不是 square.. :P

**Comment by biogerm** [comment]
然后我这才明白为什么插座要叫做 plug base。。。。。。哈哈哈哈 就 plug 就好了不用加 base... 或者叫 outlet 也可以 叫 socket 也可以。

**Comment by YinHangCode** [comment]
![qq 20170727105142](https://user-images.githubusercontent.com/15974677/28652307-9fb10a1c-72b9-11e7-8b73-877598d83a02.jpg)
有提到的，更多信息在sampleConfig.json里。

**Comment by YinHangCode** [comment]
一代也是aqara做的。以后如果再出了就叫v3喽，依次往下排，以后的事情到时候看情况吧。
plug我还以为是插头的意思，英语不是特别好，反正只是个名字，能明白啥意思就好，哈哈。

**Comment by biogerm** [comment]
哦哦 我第一次看到这句了 以为是说开关就没有仔细看 原来如此 :)

**Comment by YinHangCode** [comment]
可能是我描述的不是太好，下个版本顺便把这里改一下吧。
For more information about default name and serviceType, Please refer to file sampleConfig.json.
这样应该就没有歧义了。

**Comment by biogerm** [comment]
我看了新的首页 现在很清楚了 不错
