### ISSUE TITLE
能否支持飞利浦智睿球泡灯的控制？

### ISSUE THREAD

**Issue by riverscn** [YinHangCode/homebridge-mi-aqara#32]
智睿球泡灯也是可以通过小米网关控制的，但是目前mi-aqara不支持，能否考虑支持一下？

**Comment by riverscn** [comment]
智睿球泡灯是独立控制的，所以问题关闭，不好意思。

**Comment by YinHangCode** [comment]
灯泡应该是yeelight吧？yeelight好像有homebridge插件，可以安装yeelight的插件之后和网关这些做自动化。

**Comment by riverscn** [comment]
yeelight插件不兼容飞利浦灯泡，它是hue的。

**Comment by YinHangCode** [comment]
飞利浦hue不是直接就支持正版的homekit么？

**Comment by riverscn** [comment]
飞利浦 hue 灯泡可以直接在米家 app 控制，但不能独立支持 homekit，除非再花399元买个 hue bridge……所以按理说 hue 可以不需要 bridge 直接通过局域网控制，但也许相关协议只开放给了小米吧。

**Comment by YinHangCode** [comment]
原来是这样。。。
