### ISSUE TITLE
The v.2 button doesn't do anything.

### ISSUE THREAD

**Issue by iCarl** [YinHangCode/homebridge-mi-aqara#34]
I can use it with automations in the Mi Home app,
Other accessories works in the Home app, but presses does nothing.
No updates are being posted when I press the button in debug mode.

Using Node 6.9.5
Homebridge version 0.4.22

**Comment by YinHangCode** [comment]
search 'sensor_switch.aq2' in log, exist?

**Comment by iCarl** [comment]
I updated the firmware to latest version, and now it works
