### ISSUE TITLE
do not want to use all aqara items

### ISSUE THREAD

**Issue by theo-69** [YinHangCode/homebridge-mi-aqara#38]
How can I tell homebridge not to use all aqura items. I would like to use only a few button in homebridge.

**Comment by biogerm** [comment]
One way to do it, as what I put in use in my home, is to make a "fake" room in HomeKit, and put all unwanted accessories in that room.

Otherwise, as long as the plugins are installed, homebridge would automatically search and give you all the accessories.

**Comment by YinHangCode** [comment]
this feature will be added in the 0.4.2 version.

**Comment by theo-69** [comment]
okay thanks now working
