### ISSUE TITLE
Alarm System

### ISSUE THREAD

**Issue by theo-69** [YinHangCode/homebridge-mi-aqara#42]
Is there a plan to integrate the alarm panel from xiaomi into the plugin? Could work great with homebridge!

**Comment by YinHangCode** [comment]
this need xiaomi gateway provide relevant local network packages data.

**Comment by tomsteenbakkers** [comment]
Try this plugin. This enables you to switch the security on the gateway on (armed) and off (disarmed)

https://github.com/YinHangCode/homebridge-mi-gateway-security

**Comment by theo-69** [comment]
found it and working...
