### ISSUE TITLE
請問人體感應器第一代

### ISSUE THREAD

**Issue by phoenixlin2007** [YinHangCode/homebridge-mi-aqara#43]
整個家庭套裝都裝起來了,但是只有人體感應器第一代出現未支援,是什麼原因呢?

**Comment by YinHangCode** [comment]
显示插件不支持么？系统是ios11吧？ios11有bug 等正式版的ios11.

**Comment by phoenixlin2007** [comment]
Iphone 7 plus ios 10.3.3

**Comment by YinHangCode** [comment]
重启下homebridge试试 实在不行清下缓存

**Comment by phoenixlin2007** [comment]
我的iPhone 7p是10.3.3..但是因為ipad 10.5設為homekit hub,已經是iOS 11.beta了,所以我明天再拿apple tv4測試看看,現在情況有點怪,我的環境有philips hue2代跟homebridge(mac),但是hue2代可以使用homekit hub從外面控制,但是homebridge下面的小米設備都不行..

**Comment by phoenixlin2007** [comment]
確認是ios 11問題,就算是ios11 beta的ipad設備擺到local lan,完全沒有操作也會影響iOS 10的iPhone homekit,我的motion不是新增以後會消失,就是會出現未支援,把ios11的iPad wifi直接關掉就正常了,現在只能用apple tv4來當homekit hub
