### ISSUE TITLE
Installed snOOrz's homebridge-aqara on my server, how can i change to this one?

### ISSUE THREAD

**Issue by philboycn** [YinHangCode/homebridge-mi-aqara#5]
Hello, I've Installed snOOrz's homebridge-aqara on my homebridge server,and what i should delete first if i want change to this on?

你好，我之前安装了snOOrz's homebridge-aqara，我重新安装这个时显示不能注册同一个sid，移除了snOOrz's homebridge-aqara也不行，请问我还需要删除什么文件吗？

**Comment by YinHangCode** [comment]
cd ~/.homebridge/accessories
rm cachedAccessories
nano cachedAccessories
enter "[]"(不包括双引号) and ctrl+o save, ctrl+x exit.
execute homebridge -D

**Comment by philboycn** [comment]
Solved.Thank You!

解决了，非常感谢，已经用上了。有个显示357勒克斯的Light Sensor不知道是什么啊。

**Comment by YinHangCode** [comment]
@philboycn 那个是网关里带的亮度传感器，可以知道当前的亮度值。

**Comment by philboycn** [comment]
@YinHangCode 好的知道了。谢谢

**Comment by YinHangCode** [comment]
okay.
