### ISSUE TITLE
安装插件需要首先写好配置文件？

### ISSUE THREAD

**Issue by junyilou** [YinHangCode/homebridge-mi-aqara#50]
![458004d2-730b-4a19-9dfb-2b254fdc6229](https://user-images.githubusercontent.com/15688661/29169131-0107ce1c-7e05-11e7-84b4-6fcfdf37c105.jpeg)
npm 安装 homebridge-mi-aqara 时对配置文件是否要要求？我一直认为安装过程仅拷贝文件，插件可随 config.json 调整。这位用户似乎坚持一定要按照顺序才能够正常使用

**Comment by YinHangCode** [comment]
config.json在启动homebridge的时候读取
安装通过npm和homebridge没关系

**Comment by junyilou** [comment]
@YinHangCode 那我想的是没有问题的，感谢回复，我 Close 了。
