### ISSUE TITLE
能否脱离homekit单独使用？

### ISSUE THREAD

**Issue by iahu** [YinHangCode/homebridge-mi-aqara#67]
Hi，我有个想法，想通过程序单独控制网关。按着绿米的协议说明尝试了与网关通信后，发现只能给网关发送whois消息，却总收不到网关的回复。发现设置应该是不加密的，不知道为什么收不到反馈消息呢？

请问你的这个库有没有可能做成一个npm包供node使用？

**Comment by YinHangCode** [comment]
可以
