### ISSUE TITLE
Smart Plug doesn't work

### ISSUE THREAD

**Issue by robelsh** [YinHangCode/homebridge-mi-aqara#69]
Hello, 

I add the smart plug (zigbee) to the gateway V2, it works. 
Then the smart plug appear on the iOS Home app, but when I want to activate it, it doesn't work and the plug is still off.

There are not any errors in my homebridge logs.

I don't understand :( 

(I use the temperature and humidity sendor V1 and the contact sensor V1 without any problems.)

**Comment by ww241119786** [comment]
You should check if the content of file ~/.homebridge/config.json.
The "password" in section "platforms", it is case sensitive.
Just paste it in config.json the same it displayed in the MiJia App, do not chage to lower case.
Try it , hope it helps.....
![_20170925195652](https://user-images.githubusercontent.com/1629737/30807364-15f46cb8-a22c-11e7-8670-d328e77bc3f5.png)

**Comment by robelsh** [comment]
Thank u very much, I wrote the password in lower case, my bad
