### ISSUE TITLE
homebridge-aqara is normal but homebridge-mi-aqara not being able to recognize byhomekit

### ISSUE THREAD

**Issue by NathanDai** [YinHangCode/homebridge-mi-aqara#76]

**Comment by NathanDai** [comment]
this is in homebridge-aqara
![img_0002](https://user-images.githubusercontent.com/28701315/31577065-8b756056-b13a-11e7-8a4c-08df53b17efb.png)

**Comment by NathanDai** [comment]
this is in homebridge-mi-aqara 
![0ff9fd8bcc943bac6b637c533f4c1440](https://user-images.githubusercontent.com/28701315/31577122-7226d3fe-b13b-11e7-8613-52523dfa6157.jpg)

**Comment by weikuan1024** [comment]
两个插件不要同时装！

**Comment by iCarl** [comment]
Do you have both plugins installed at the same time?

**Comment by weikuan1024** [comment]
i uninstall one，and ok，thxs

发自我的 iPhone
