### ISSUE TITLE
how is the losing room situation

### ISSUE THREAD

**Issue by theo-69** [YinHangCode/homebridge-mi-aqara#8]
Hi there I am using another aqara plugin and the items are always loosing the room and name, is this the same with this plugin?

**Comment by rqui** [comment]
No, this pluguin works much better than others.

**Comment by theo-69** [comment]
might be but, does it have the "back to standard room" Problem?

**Comment by rqui** [comment]
No, keeps the room information and name, and the accessories dosen't dissapear all the time.

**Comment by theo-69** [comment]
okay I will try ;-)

**Comment by YinHangCode** [comment]
another aqara plugin is usually based on [homebridge-aqara](https://github.com/snOOrz/homebridge-aqara). homebridge-aqara use value last update time as the delete condition, so plugin will deleted that there is no value update for a period of time.
homebridge-mi-aqara use heartbeat last send time as the delete condition, official document description: device use battery every one hour send a heartbeat information, device use electric every ten minute send a heartbeat information. so it should not appear loosing the room and name.

**Comment by theo-69** [comment]
Thats Great news, will try and report back.

**Comment by YinHangCode** [comment]
^_^
