### ISSUE TITLE
Loading plugin ok, changes result in error

### ISSUE THREAD

**Issue by tomsteenbakkers** [YinHangCode/homebridge-mi-aqara#80]
I have the plugin installed and the gateway shows up in Homekit. When I use the Mi App the Homekit shows not the changes. The Gateway tile says "No Response".

 I get the following error in the homebridge log:

_Oct 23 12:42:52 RaspberryPi homebridge[4597]: [10/23/2017, 12:42:52 PM] [MiAqaraPlatform] [ERROR]TypeError: Cannot read property 'gatewaySid' of null_

This is how the config.json files looks like:

                {
                        "platform": "MiAqaraPlatform",
                        "sid": ["286c07fa36ff"],
                        "password": ["xxxa7abb88fxxxxx"],
                        "gateways":     
                        {
                                "286C07FA36FF": "xxxa7abb88fxxxxx"
                        }
                }

**Comment by YinHangCode** [comment]
···
{
    "platform": "MiAqaraPlatform",
    "gateways": {
        "286c07fa36ff": "xxxa7abb88fxxxxx"
    }
}
···

**Comment by tomsteenbakkers** [comment]
Hi,

Thanks for the response. It solved the issue that HomeKit now sees immediately the changes made in de Mi App. But when I try to change i.e. the color than the following error occurs in de log:

`Oct 23 15:03:39 RaspberryPi homebridge[4911]: [10/23/2017, 3:03:39 PM] [MiAqaraPlatform] [ERROR]Error: Invalid key`

By switching the gateway on, 3 error items are logged (all the same)l. When changing the color 6 error items are logged (all the same).

Any idea?

the positive part is that restart the homebridge is not necessary, the error will set the item in homekit for some seconds in No Update but after a few second it shows the right status of the gateway.

**Comment by a900927** [comment]
pls check your password

**Comment by YinHangCode** [comment]
rules:
mac address: **lower case without colon**
password: **keep original and case sensitive**

**Comment by tomsteenbakkers** [comment]
OK, the rules did the trick. Is was for me a little confusing. Sometimes it's lower case and sometimes  case sensitive. Now everything is working! Thanks for the quick response.

**Comment by tomsteenbakkers** [comment]
Thanks all! Closing the issue.

**Comment by xrust83** [comment]
[16/08/2021, 02:17:11] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"gateway","sid":"04cf8ca9d72e","data":"{\"rgb\":1250651135, \"key\": \"f47d23c77a4d45b9eaa2936b98bf797a\"}"}
[16/08/2021, 02:17:11] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"gateway","sid":"04cf8ca9d72e","data":"{\"rgb\":1250651135, \"key\": \"f47d23c77a4d45b9eaa2936b98bf797a\"}"}
