### ISSUE TITLE
ElectricCurtain does not appear.

### ISSUE THREAD

**Issue by Km81** [YinHangCode/homebridge-mi-aqara#81]
Version 0.5.3 worked well.
In version 0.6.2, it does not appear in the HomeKit.

Please update it.

**Comment by a900927** [comment]
update your config

**Comment by Km81** [comment]
I did it.
Also I changed the name of device 'ElectricCurtain_WindowCovering'.

**Comment by a900927** [comment]
maybe you can delete the bridge and cache ,then re-add the bridge

**Comment by Km81** [comment]
Sorry, I did several times.
Do you appear 'ElectricCurtain' after updating 0.6.2  ?

**Comment by a900927** [comment]
author say he will test tomorrow,maybe you can roll back version 0.5.x

**Comment by Km81** [comment]
After rolling back 0.5.3, the issue was gone.
Thanks for your advice.

**Comment by beviz** [comment]
0.6.1, 0.6.2 都无法获取配件列表

**Comment by YinHangCode** [comment]
@beviz emmm, what's the meaning of "fetch accessories list"?

**Comment by beviz** [comment]
使用这两个版本在 家庭 app 里不显示任何配件，而使用 0.5.3 后可获取到。

另外再提几个问题吧：

1. 非 zigbee 版本的插座，能显示到列表内，但无法操作，也获取不到实时状态，使用 homebridge-miio 则正常。虽然没有被列入支持，希望要么不显示，要么显示了就支持操作
2. 按钮配件可以显示在列表内，但无法操作。
3. 温湿度传感器，温度和湿度会各获取三个配件，一共六个，但各只有一个显示正常数值，其它的都是显示 100摄氏度和 0% 湿度。

**Comment by YinHangCode** [comment]
@beviz 
1 Wi-Fi插座 不存在的
2 清缓存
3 清缓存

**Comment by beviz** [comment]
用的 homebridge 的 docker，缓存清过一万遍了的，删掉两个文件夹，container 也 rm 掉，往复操作了好几天的，还是一样。

Wi-Fi 插座不存在啥意思，

**Comment by a900927** [comment]
用docker不累吗。。

**Comment by a900927** [comment]
1.这个插件只支持aqara
2.无法操作，请检查局域网密码（或者你刷新一个密码）
3.））

**Comment by beviz** [comment]
docker 不用考虑环境要求、版本冲突、自动启动等问题，并且我是在群辉里跑的，任何机器，扔进去几个配置文件改改，直接就能启动，能用 docker 当然优先用。

1. 我知道不支持非 zigbee 版本的，我的意思，要么你直接就不要显示出来，要么就支持上。又显示又按不了，逼死强迫症的。
2. 局域网密码多次校验和重新生成过，也用 android 重新生成过纯小写的试过，但依旧不好使。
3. ？

**Comment by a900927** [comment]
你先用回5.x版本吧。新版有问题，等更新吧。不过你说会显示非zigbee设备这个应该不会吧，建议你一个一个插件排查

**Comment by YinHangCode** [comment]
@beviz 
这个程序只能用zigbee的设备 所以wifi插座是不存在的。
不能控制是密码错了
一个温湿度传感器只会出现一个温度传感器和一个湿度传感器，你说出现多个怀疑多出来的是0.5.x版本的。

**Comment by YinHangCode** [comment]
@a900927  目前已知问题是窗帘，暂时还没发现其它问题，下个版本主要是加是否自动同步用户自定义功能。

**Comment by a900927** [comment]
@YinHangCode 我知道啊。我天天在群主窥视你;^)

**Comment by YinHangCode** [comment]
@a900927  好吧 = =#

**Comment by YinHangCode** [comment]
@Km81 update to 0.6.3

**Comment by beviz** [comment]
@YinHangCode 圈选的灯一个可控一个不可控，是同一个插座，类型改成了灯，不可控的那个就是我提到的。还有多出来的两个 100 度，四个不可控的按钮。无论如何重置缓存、重新安装，一直存在。

![6dfa9a06-eeed-4f39-b55a-6bb9386704e9](https://user-images.githubusercontent.com/1106312/32452561-d96ef8f4-c354-11e7-9b35-7f3d31d3295e.jpeg)
