### ISSUE TITLE
Key question 

### ISSUE THREAD

**Issue by Radstake** [YinHangCode/homebridge-mi-aqara#86]
Hi,
I wanted my own command over UDP, so I reused code like:

```
var cipher = crypto.createCipheriv('aes-128-cbc', that.ConfigUtil.getGatewayPasswordByGatewaySid(gateway['sid']), iv);
var gatewayToken = gateway['token'];
var key = cipher.update(gatewayToken, "ascii", "hex");
cipher.final('hex'); // Useless data, don't know why yet.
command = command.replace('${key}', key);
console.log("command: "+command);
```

But when I use this homeberidge plugin and dump the command everytime a new key is generated that works, but when I do it, I always get the same key, that doesn't work. How do I generate the correct key that I can use over UDP? Thanks in advance!!!

**Comment by YinHangCode** [comment]
every gateway heartbeat will changed token. so must save newest token and use it encode.

**Comment by Radstake** [comment]
ah! great thank you!

**Comment by Radstake** [comment]
works perfect!
