### ISSUE TITLE
Anyone experience with playing mid?

### ISSUE THREAD

**Issue by Radstake** [YinHangCode/homebridge-mi-aqara#89]
Hi!

According to the specs I can play custom uploaded sounds with:

`{"cmd":"write","model":"gateway","sid":"","short_id":0,"data":"{\"mid\": \"10001'\", \"key\" : \"'\"}" }`

But when I do, I always get the default alarm sound, even when I try with 10000, that's the code to stop playing. Has something changed, or am I doing something wrong?
The sounds are uploaded correctly, because I can play them when using the app.

PS thank you for maintaining and developing this great plugin!

**Comment by YinHangCode** [comment]
It should be like this:
"mid: 10000" mean stop play.
mid valid value: 0-8,10-13,20-29.
more than 10000 is user upload voice.

**Comment by Radstake** [comment]
Yes I know. I have uploaded 1 voice, so it should be 10001, but it doens't work...

**Comment by Radstake** [comment]
I noticed, i deleted one and recorded it again, it became 10002 and 1 will remain empty!
