### ISSUE TITLE
小白问题

### ISSUE THREAD

**Issue by happylichuanxi** [YinHangCode/homebridge-mi-aqara#9]
小白问题，大侠们见笑了。

**Comment by happylichuanxi** [comment]
请问如果我之前安装了别人的aqara插件，想要更换为此插件，需要卸载之前安装的插件吗？该如何操作？来自一只linux小白。

**Comment by a900927** [comment]
应该不需要吧。安装然后配置config.json文件就可以了，但是最好把旧的aqara黎到其它地方。要用再移回来就可以了

**Comment by liliass** [comment]
有人能出一个教程吗？

Linux小白

**Comment by YinHangCode** [comment]
最好删掉以前的，因为每个配件有唯一的UUID，homebridge-mi-aqara的UUID计算方式和homebridge-aqara的一样 没改，所以UUID会相同 冲突。。。。

**Comment by happylichuanxi** [comment]
@YinHangCode 非常感谢大侠提供这个好用的插件，还要抽空给我这样的小白讲解！

**Comment by YinHangCode** [comment]
@happylichuanxi  没什么 举手之劳而已
